### ISSUE TITLE
Dockerfiles' numpy version needs to be fixed and retained when installing tensorpack

### ISSUE THREAD

**Issue by Cpruce** [aws-samples/amazon-eks-machine-learning-with-terraform-and-kubeflow#4]
`RUN pip install --ignore-installed -e /tensorpack` installs numpy 1.18 now, which breaks the loading of data with pycocotools:

![Screen Shot 2020-01-06 at 2 36 35 PM](https://user-images.githubusercontent.com/2712171/72016329-6eef4580-3218-11ea-8c7c-8991b7818f53.png)

This can be resolved by fixing the version of numpy in the dockerfile and removing the `--ignore-installed` from the tensorpack pip install. Currently searching for the latest numpy version that works. Will submit pull request afterwards.

**Comment by Cpruce** [comment]
Can't directly create a pull request as I am not a contributor or collaborator to the repo.

Changes:

Add `RUN pip install numpy==1.17.5` above `RUN pip install awscli` and remove `--ignore-installed` from the last line in both `container/Dockerfile` and `container-optimized/Dockerfile`.

I can also fork the repository and submit a pull request that way if it is easier.

**Comment by ajayvohra2005** [comment]
Merged pull request fixing this issue
